%YAML:1.0
---
config:
   liveImagePort: 2000
   snapshotPort: 2001
   resolution: [ 1920, 1080 ]
   snapshotInterpolationMethod: 1
   maxSnapshotRotateDegrees: 90.
   training:
      backgroundFilename: ""
      liveRect: [ 420, 125, 1080, 150 ]
      snapshotRects:
         - [ 100, 400, 720, 100 ]
         - [ 1100, 400, 720, 100 ]
         - [ 100, 550, 720, 100 ]
         - [ 1100, 550, 720, 100 ]
         - [ 100, 700, 720, 100 ]
         - [ 1100, 700, 720, 100 ]
         - [ 100, 850, 720, 100 ]
         - [ 1100, 850, 720, 100 ]
   testing:
      backgroundFilename: ""
      bestSnapshotPort: 2002
      liveRect: [ 420, 125, 1080, 150 ]
      bestRect: [ 420, 400, 1080, 150 ]
      differenceRect: [ 420, 600, 1080, 150 ]
      ridfRect: [ 420, 800, 1080, 150 ]
      ridfAxisRect: [ 420, 800, 1080, 150 ]
      ridfBackgroundColour: [ 255, 255, 255 ]
      ridfLineColour: [ 0, 0, 0 ]
      ridfLineThickness: 2
