%YAML:1.0
---
config:
   liveImagePort: 2000
   snapshotPort: 2001
   resolution: [ 1920, 1080 ]
   snapshotInterpolationMethod: 1
   maxSnapshotRotateDegrees: 90.
   training:
      backgroundFilename: "background_training.png"
      liveRect: [ 420, 75, 1080, 150 ]
      snapshotRects:
         - [ 210, 360, 720, 100 ]
         - [ 980, 360, 720, 100 ]
         - [ 210, 510, 720, 100 ]
         - [ 980, 510, 720, 100 ]
         - [ 210, 660, 720, 100 ]
         - [ 980, 660, 720, 100 ]
         - [ 210, 810, 720, 100 ]
         - [ 980, 810, 720, 100 ]
   testing:
      backgroundFilename: "background_testing.png"
      bestSnapshotPort: 2002
      liveRect: [ 420, 75, 1080, 150 ]
      bestRect: [ 420, 305, 1080, 150 ]
      differenceRect: [ 420, 550, 1080, 150 ]
      ridfAxisRect: [ 420, 790, 1080, 150 ]
      ridfBackgroundColour: [ 255, 255, 255 ]
      ridfLineColour: [ 0, 0, 0 ]
      ridfLineThickness: 2
