%YAML:1.0
---
config:
   shouldUseHOG: 0
   shouldUseBinaryImage: 0
   shouldUseTrueBinaryImage: 1
   shouldUseHorizonVector: 0
   shouldTrain: 1
   shouldUseInfoMax: 0
   shouldUseMBArdin: 0
   shouldUseMBHOG: 0
   shouldSaveTestingDiagnostic: 0
   shouldStreamOutput: 0
   outputPath: path
   testingSuffix: _pm
   maxSnapshotRotateDegrees: 90.
   unwrapRes: [ 90, 20 ]
   maskImageFilename: ""
   watershedMarkerImageFilename: "segmentation_90_20.png"
   numHOGOrientations: 8
   numHOGPixelsPerCell: 10
   joystickDeadzone: 2.5000000000000000e-01
   autoTrain: 1
   trainInterval: 100.
   motorCommandInterval: 1000.
   motorTurnCommandInterval: 400.
   serverListenPort: 2000
   moveSpeed: 5.0000000000000000e-01
   turnThresholds:
      -
         - 5.
         - 1.5000000894069672e-01
      -
         - 20.
         - 2.0000001788139343e-01
